import {
  Account,
  Contact,
  Opportunity,
  Task,
  Note,
  Activity,
  FileDocument,
  User,
} from './types';

export const DEMO_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Janaki Pawar',
    email: 'janakipawar2004@gmail.com',
    role: 'sales',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    title: 'Senior Enterprise Account Executive',
    department: 'Enterprise Sales',
    phone: '+1 (415) 890-2134',
    bio: 'Focused on Fortune 500 SaaS and Digital Transformation accounts with 8+ years experience.',
    preferences: {
      currency: 'USD',
      theme: 'light',
      compactView: false,
      emailNotifications: true,
      taskReminders: true,
    },
  },
  {
    id: 'usr-2',
    name: 'Alex Chen',
    email: 'alex.chen@crmcompany.com',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    title: 'CRM Administrator & RevOps Lead',
    department: 'Revenue Operations',
    phone: '+1 (415) 762-9011',
    bio: 'Managing CRM infrastructure, integrations, compliance, and user roles.',
    preferences: {
      currency: 'USD',
      theme: 'light',
      compactView: true,
      emailNotifications: true,
      taskReminders: false,
    },
  },
  {
    id: 'usr-3',
    name: 'Sarah Miller',
    email: 'sarah.miller@crmcompany.com',
    role: 'management',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    title: 'VP of Global Sales',
    department: 'Executive Leadership',
    phone: '+1 (415) 431-7782',
    bio: 'Overseeing North America and EMEA revenue growth, pipeline health, and quarterly quotas.',
    preferences: {
      currency: 'USD',
      theme: 'light',
      compactView: false,
      emailNotifications: true,
      taskReminders: true,
    },
  },
];

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc-1',
    name: 'Apex Cloud Solutions Inc',
    ownerId: 'usr-1',
    ownerName: 'Janaki Pawar',
    type: 'Customer',
    accountNumber: 'ACC-89211',
    website: 'https://apexcloudsolutions.io',
    phone: '+1 (415) 555-0192',
    industry: 'Technology',
    ownership: 'Public',
    rating: 'Hot',
    annualRevenue: 125000000,
    employees: 1450,
    businessSegment: 'Enterprise',
    customerStatus: 'Active',
    leadSource: 'Partner Referral',
    billingStreet: '100 Montgomery St, Suite 1800',
    billingCity: 'San Francisco',
    billingState: 'CA',
    billingPostalCode: '94104',
    billingCountry: 'United States',
    shippingStreet: '100 Montgomery St, Suite 1800',
    shippingCity: 'San Francisco',
    shippingState: 'CA',
    shippingPostalCode: '94104',
    shippingCountry: 'United States',
    sameAsBilling: true,
    description: 'Leading hybrid cloud infrastructure provider expanding their AI-driven customer intelligence suite.',
    notes: 'Key decision-maker is CTO Marcus Vance. Renewal coming up in Q4.',
    createdAt: '2026-03-12T10:00:00Z',
    updatedAt: '2026-08-15T14:30:00Z',
    createdBy: 'Janaki Pawar',
    modifiedBy: 'Janaki Pawar',
  },
  {
    id: 'acc-2',
    name: 'Quantum Health BioTech',
    ownerId: 'usr-1',
    ownerName: 'Janaki Pawar',
    type: 'Prospect',
    accountNumber: 'ACC-77419',
    website: 'https://quantumhealth.bio',
    phone: '+1 (617) 555-0143',
    industry: 'Healthcare & Life Sciences',
    ownership: 'Private',
    rating: 'Hot',
    annualRevenue: 48000000,
    employees: 380,
    businessSegment: 'Mid-Market',
    customerStatus: 'Pending',
    leadSource: 'Visiting Card OCR',
    billingStreet: '400 Technology Square',
    billingCity: 'Cambridge',
    billingState: 'MA',
    billingPostalCode: '02139',
    billingCountry: 'United States',
    sameAsBilling: true,
    description: 'Specialized clinical genomics research company looking to consolidate enterprise customer data and compliance workflows.',
    notes: 'Met VP of Informatics Dr. Elena Rostova at Biotech Summit. Very interested in automated OCR & audit trails.',
    createdAt: '2026-05-18T09:15:00Z',
    updatedAt: '2026-08-18T11:20:00Z',
    createdBy: 'Janaki Pawar',
    modifiedBy: 'Janaki Pawar',
  },
  {
    id: 'acc-3',
    name: 'Vertex Financial Group',
    ownerId: 'usr-1',
    ownerName: 'Janaki Pawar',
    type: 'Customer',
    accountNumber: 'ACC-61023',
    website: 'https://vertexfinancial.com',
    phone: '+1 (212) 555-0188',
    industry: 'Financial Services',
    ownership: 'Public',
    rating: 'Warm',
    annualRevenue: 340000000,
    employees: 2800,
    businessSegment: 'Enterprise',
    customerStatus: 'Active',
    leadSource: 'Direct',
    billingStreet: '200 Park Avenue, 35th Floor',
    billingCity: 'New York',
    billingState: 'NY',
    billingPostalCode: '10166',
    billingCountry: 'United States',
    sameAsBilling: true,
    description: 'Tier-1 wealth management and institutional advisory firm adopting our CRM platform for 400+ relationship managers.',
    notes: 'High compliance requirements (SOC2 & FINRA). Security review passed in July.',
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-08-10T16:45:00Z',
    createdBy: 'Janaki Pawar',
    modifiedBy: 'Janaki Pawar',
  },
  {
    id: 'acc-4',
    name: 'Helios Advanced Manufacturing',
    ownerId: 'usr-2',
    ownerName: 'Alex Chen',
    type: 'Prospect',
    accountNumber: 'ACC-55201',
    website: 'https://helios-mfg.de',
    phone: '+49 89 2444 8900',
    industry: 'Manufacturing',
    ownership: 'Subsidiary',
    rating: 'Warm',
    annualRevenue: 85000000,
    employees: 720,
    businessSegment: 'Mid-Market',
    customerStatus: 'Pending',
    leadSource: 'Web Form',
    billingStreet: 'Maximilianstraße 35',
    billingCity: 'Munich',
    billingState: 'Bavaria',
    billingPostalCode: '80539',
    billingCountry: 'Germany',
    sameAsBilling: true,
    description: 'Precision robotics and IoT component manufacturer modernizing supply chain partner management.',
    notes: 'Requested a multilingual demo and quotation for 120 seats.',
    createdAt: '2026-06-01T11:00:00Z',
    updatedAt: '2026-08-12T10:10:00Z',
    createdBy: 'Alex Chen',
    modifiedBy: 'Alex Chen',
  },
  {
    id: 'acc-5',
    name: 'BlueSky Omni Retailers',
    ownerId: 'usr-1',
    ownerName: 'Janaki Pawar',
    type: 'Prospect',
    accountNumber: 'ACC-43198',
    website: 'https://blueskyretail.com',
    phone: '+1 (312) 555-0177',
    industry: 'Retail & eCommerce',
    ownership: 'Private',
    rating: 'Cold',
    annualRevenue: 22000000,
    employees: 190,
    businessSegment: 'SMB',
    customerStatus: 'Pending',
    leadSource: 'Event',
    billingStreet: '500 N Michigan Ave',
    billingCity: 'Chicago',
    billingState: 'IL',
    billingPostalCode: '60611',
    billingCountry: 'United States',
    sameAsBilling: true,
    description: 'Fast-growing omnichannel lifestyle brand needing unified customer journey tracking.',
    notes: 'Re-evaluating CRM budget in Q3.',
    createdAt: '2026-07-15T14:20:00Z',
    updatedAt: '2026-08-05T09:30:00Z',
    createdBy: 'Janaki Pawar',
    modifiedBy: 'Janaki Pawar',
  },
];

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'cnt-1',
    salutation: 'Mr.',
    firstName: 'Marcus',
    lastName: 'Vance',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    accountId: 'acc-1',
    accountName: 'Apex Cloud Solutions Inc',
    jobTitle: 'Chief Technology Officer',
    department: 'Engineering & Product',
    email: 'marcus.vance@apexcloudsolutions.io',
    phone: '+1 (415) 555-0192',
    mobile: '+1 (415) 932-1104',
    linkedInUrl: 'https://linkedin.com/in/marcus-vance-tech',
    street: '100 Montgomery St',
    city: 'San Francisco',
    state: 'CA',
    postalCode: '94104',
    country: 'United States',
    preferredContactMethod: 'Email',
    ownerId: 'usr-1',
    ownerName: 'Janaki Pawar',
    source: 'Partner Referral',
    notes: 'Primary executive sponsor for cloud CRM rollout. Prefers morning meetings on Tuesdays and Thursdays.',
    createdAt: '2026-03-12T10:30:00Z',
    updatedAt: '2026-08-15T14:30:00Z',
  },
  {
    id: 'cnt-2',
    salutation: 'Dr.',
    firstName: 'Elena',
    lastName: 'Rostova',
    profileImage: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    accountId: 'acc-2',
    accountName: 'Quantum Health BioTech',
    jobTitle: 'VP of Clinical Informatics',
    department: 'Bioinformatics & Research',
    email: 'e.rostova@quantumhealth.bio',
    phone: '+1 (617) 555-0143',
    mobile: '+1 (617) 843-9921',
    linkedInUrl: 'https://linkedin.com/in/elena-rostova-phd',
    street: '400 Technology Square',
    city: 'Cambridge',
    state: 'MA',
    postalCode: '02139',
    country: 'United States',
    preferredContactMethod: 'Mobile',
    ownerId: 'usr-1',
    ownerName: 'Janaki Pawar',
    source: 'Visiting Card OCR',
    notes: 'Card scanned via OCR at Boston Health Innovation Summit. Leads 40+ data scientists.',
    cardImageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    createdAt: '2026-05-18T09:30:00Z',
    updatedAt: '2026-08-18T11:20:00Z',
  },
  {
    id: 'cnt-3',
    salutation: 'Ms.',
    firstName: 'Victoria',
    lastName: 'Sterling',
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    accountId: 'acc-3',
    accountName: 'Vertex Financial Group',
    jobTitle: 'Managing Director, Head of Client Ops',
    department: 'Wealth Management Operations',
    email: 'vsterling@vertexfinancial.com',
    phone: '+1 (212) 555-0188',
    mobile: '+1 (917) 441-2098',
    linkedInUrl: 'https://linkedin.com/in/victoria-sterling-finance',
    street: '200 Park Avenue',
    city: 'New York',
    state: 'NY',
    postalCode: '10166',
    country: 'United States',
    preferredContactMethod: 'Email',
    ownerId: 'usr-1',
    ownerName: 'Janaki Pawar',
    source: 'Direct',
    notes: 'Championed contract sign-off for Phase 1. Currently reviewing Phase 2 expansion for international wealth advisors.',
    createdAt: '2026-02-10T08:30:00Z',
    updatedAt: '2026-08-10T16:45:00Z',
  },
  {
    id: 'cnt-4',
    salutation: 'Mr.',
    firstName: 'Klaus',
    lastName: 'Weber',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    accountId: 'acc-4',
    accountName: 'Helios Advanced Manufacturing',
    jobTitle: 'Director of Global Procurement',
    department: 'Supply Chain Operations',
    email: 'klaus.weber@helios-mfg.de',
    phone: '+49 89 2444 8900',
    mobile: '+49 171 902 3341',
    street: 'Maximilianstraße 35',
    city: 'Munich',
    state: 'Bavaria',
    postalCode: '80539',
    country: 'Germany',
    preferredContactMethod: 'Email',
    ownerId: 'usr-2',
    ownerName: 'Alex Chen',
    source: 'Web Form',
    notes: 'Requested security whitepaper and SLA specifications in German and English.',
    createdAt: '2026-06-01T11:30:00Z',
    updatedAt: '2026-08-12T10:10:00Z',
  },
  {
    id: 'cnt-5',
    salutation: 'Ms.',
    firstName: 'Amara',
    lastName: 'Patel',
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    accountId: 'acc-5',
    accountName: 'BlueSky Omni Retailers',
    jobTitle: 'Head of Customer Experience & Growth',
    department: 'Marketing & CX',
    email: 'amara.patel@blueskyretail.com',
    phone: '+1 (312) 555-0177',
    mobile: '+1 (312) 670-8819',
    street: '500 N Michigan Ave',
    city: 'Chicago',
    state: 'IL',
    postalCode: '60611',
    country: 'United States',
    preferredContactMethod: 'WhatsApp',
    ownerId: 'usr-1',
    ownerName: 'Janaki Pawar',
    source: 'Event',
    notes: 'Met at RetailTech Chicago. Seeking an easy mobile and desktop CRM for in-store concierge staff.',
    createdAt: '2026-07-15T14:45:00Z',
    updatedAt: '2026-08-05T09:30:00Z',
  },
];

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-1',
    name: 'Apex - Global Cloud Intelligence Rollout',
    accountId: 'acc-1',
    accountName: 'Apex Cloud Solutions Inc',
    primaryContactId: 'cnt-1',
    primaryContactName: 'Marcus Vance',
    ownerId: 'usr-1',
    ownerName: 'Janaki Pawar',
    amount: 320000,
    probability: 80,
    expectedRevenue: 256000,
    stage: 'Negotiation',
    status: 'Open',
    expectedCloseDate: '2026-09-30',
    leadSource: 'Partner Referral',
    nextStep: 'Finalize master service agreement with legal and procurement by Sep 15',
    description: 'Enterprise 3-year subscription for 500 licenses, including custom API connectors and 24/7 dedicated support.',
    createdAt: '2026-04-10T10:00:00Z',
    updatedAt: '2026-08-19T15:00:00Z',
  },
  {
    id: 'opp-2',
    name: 'Quantum Health - Genomics CRM & Compliance Suite',
    accountId: 'acc-2',
    accountName: 'Quantum Health BioTech',
    primaryContactId: 'cnt-2',
    primaryContactName: 'Elena Rostova',
    ownerId: 'usr-1',
    ownerName: 'Janaki Pawar',
    amount: 185000,
    probability: 60,
    expectedRevenue: 111000,
    stage: 'Proposal',
    status: 'Open',
    expectedCloseDate: '2026-10-15',
    leadSource: 'Visiting Card OCR',
    nextStep: 'Schedule technical deep-dive and HIPAA compliance review with IT team',
    description: 'HIPAA-compliant CRM workspace with automated visiting card OCR for medical conferences and clinical trial stakeholder tracking.',
    createdAt: '2026-05-20T11:00:00Z',
    updatedAt: '2026-08-18T16:20:00Z',
  },
  {
    id: 'opp-3',
    name: 'Vertex - Phase 2 International Advisory Expansion',
    accountId: 'acc-3',
    accountName: 'Vertex Financial Group',
    primaryContactId: 'cnt-3',
    primaryContactName: 'Victoria Sterling',
    ownerId: 'usr-1',
    ownerName: 'Janaki Pawar',
    amount: 450000,
    probability: 100,
    expectedRevenue: 450000,
    stage: 'Closed Won',
    status: 'Won',
    expectedCloseDate: '2026-08-10',
    actualCloseDate: '2026-08-10',
    wonLostReason: 'Superior compliance architecture, seamless UX, and responsive team during pilot.',
    leadSource: 'Direct',
    nextStep: 'Kickoff implementation on Sep 1 with wealth management teams in London and Zurich',
    description: 'Expansion package to onboard 350 relationship managers across London, Zurich, and Singapore offices.',
    createdAt: '2026-02-15T09:00:00Z',
    updatedAt: '2026-08-10T17:00:00Z',
  },
  {
    id: 'opp-4',
    name: 'Helios - Smart Manufacturing Supply CRM',
    accountId: 'acc-4',
    accountName: 'Helios Advanced Manufacturing',
    primaryContactId: 'cnt-4',
    primaryContactName: 'Klaus Weber',
    ownerId: 'usr-2',
    ownerName: 'Alex Chen',
    amount: 140000,
    probability: 40,
    expectedRevenue: 56000,
    stage: 'Needs Analysis',
    status: 'Open',
    expectedCloseDate: '2026-11-20',
    leadSource: 'Web Form',
    nextStep: 'Complete technical requirement questionnaire with European operations team',
    description: 'Modern supplier relation management solution with ERP synchronization capabilities.',
    createdAt: '2026-06-05T14:00:00Z',
    updatedAt: '2026-08-12T10:10:00Z',
  },
  {
    id: 'opp-5',
    name: 'BlueSky - Omnichannel Loyalty & Lead Management',
    accountId: 'acc-5',
    accountName: 'BlueSky Omni Retailers',
    primaryContactId: 'cnt-5',
    primaryContactName: 'Amara Patel',
    ownerId: 'usr-1',
    ownerName: 'Janaki Pawar',
    amount: 75000,
    probability: 20,
    expectedRevenue: 15000,
    stage: 'Qualification',
    status: 'Open',
    expectedCloseDate: '2026-12-05',
    leadSource: 'Event',
    nextStep: 'Follow up with Amara post-summer brand restructuring',
    description: 'Standard tier CRM deployment for 25 store managers and digital growth team.',
    createdAt: '2026-07-20T16:00:00Z',
    updatedAt: '2026-08-05T09:30:00Z',
  },
  {
    id: 'opp-6',
    name: 'Pinnacle Logistics - Fleet CRM Pilot',
    accountId: 'acc-1',
    accountName: 'Apex Cloud Solutions Inc',
    primaryContactId: 'cnt-1',
    primaryContactName: 'Marcus Vance',
    ownerId: 'usr-1',
    ownerName: 'Janaki Pawar',
    amount: 95000,
    probability: 0,
    expectedRevenue: 0,
    stage: 'Closed Lost',
    status: 'Lost',
    expectedCloseDate: '2026-07-15',
    actualCloseDate: '2026-07-15',
    wonLostReason: 'Budget was reallocated to warehouse automation hardware during Q2 review.',
    leadSource: 'Phone Inquiry',
    nextStep: 'Revisit conversation in Q1 next fiscal year',
    description: 'Evaluation for dedicated fleet dispatcher CRM add-on.',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-07-15T12:00:00Z',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk-1',
    title: 'Review Apex Cloud legal clauses and redlines with General Counsel',
    description: 'Check data retention and liability cap clauses before sending back revised draft.',
    priority: 'High',
    status: 'In Progress',
    dueDate: '2026-08-22',
    dueTime: '14:00',
    assignedToId: 'usr-1',
    assignedToName: 'Janaki Pawar',
    relatedToType: 'Opportunity',
    relatedToId: 'opp-1',
    relatedToName: 'Apex - Global Cloud Intelligence Rollout',
    createdAt: '2026-08-19T09:00:00Z',
  },
  {
    id: 'tsk-2',
    title: 'Send Quantum Health HIPAA compliance architecture deck',
    description: 'Dr. Elena Rostova requested whitepaper highlighting automated visiting card OCR data handling policies.',
    priority: 'High',
    status: 'Not Started',
    dueDate: '2026-08-23',
    dueTime: '10:00',
    assignedToId: 'usr-1',
    assignedToName: 'Janaki Pawar',
    relatedToType: 'Contact',
    relatedToId: 'cnt-2',
    relatedToName: 'Elena Rostova',
    createdAt: '2026-08-18T11:30:00Z',
  },
  {
    id: 'tsk-3',
    title: 'Coordinate London onboarding schedule with Victoria Sterling',
    description: 'Confirm dates and user roster for Phase 2 wealth management CRM kickoff.',
    priority: 'Medium',
    status: 'In Progress',
    dueDate: '2026-08-25',
    dueTime: '15:30',
    assignedToId: 'usr-1',
    assignedToName: 'Janaki Pawar',
    relatedToType: 'Account',
    relatedToId: 'acc-3',
    relatedToName: 'Vertex Financial Group',
    createdAt: '2026-08-11T08:00:00Z',
  },
  {
    id: 'tsk-4',
    title: 'Send German product catalog & pricing sheet to Klaus Weber',
    description: 'Prepare custom quote for 120 seats with European data residency.',
    priority: 'Medium',
    status: 'Not Started',
    dueDate: '2026-08-26',
    dueTime: '11:00',
    assignedToId: 'usr-2',
    assignedToName: 'Alex Chen',
    relatedToType: 'Opportunity',
    relatedToId: 'opp-4',
    relatedToName: 'Helios - Smart Manufacturing Supply CRM',
    createdAt: '2026-08-12T10:15:00Z',
  },
  {
    id: 'tsk-5',
    title: 'Prepare Q3 Board Executive Sales Performance Pack',
    description: 'Summarize pipeline conversion rates, top accounts, and OCR business card adoption metrics.',
    priority: 'High',
    status: 'In Progress',
    dueDate: '2026-08-28',
    dueTime: '17:00',
    assignedToId: 'usr-3',
    assignedToName: 'Sarah Miller',
    relatedToType: 'General',
    createdAt: '2026-08-15T09:00:00Z',
  },
];

export const INITIAL_NOTES: Note[] = [
  {
    id: 'not-1',
    title: 'Apex Cloud - Procurement Strategy & Discount Guardrails',
    content: 'Marcus Vance confirmed approval from CFO. They requested a 5% multi-year discount. We agreed on 5% in exchange for 3-year upfront payment and case study participation.',
    tags: ['Negotiation', 'Enterprise', 'Pricing'],
    category: 'Strategy',
    relatedToType: 'Opportunity',
    relatedToId: 'opp-1',
    relatedToName: 'Apex - Global Cloud Intelligence Rollout',
    authorId: 'usr-1',
    authorName: 'Janaki Pawar',
    isPinned: true,
    createdAt: '2026-08-17T14:20:00Z',
    updatedAt: '2026-08-17T14:20:00Z',
  },
  {
    id: 'not-2',
    title: 'Quantum Health BioTech - Boston Summit Meeting Summary',
    content: 'Met Dr. Elena Rostova at the AI in Genomics booth. She highlighted pain points around decentralized contact management across clinical partners. Card scanned seamlessly with OCR.',
    tags: ['OCR', 'Healthcare', 'Conference'],
    category: 'Meeting',
    relatedToType: 'Contact',
    relatedToId: 'cnt-2',
    relatedToName: 'Elena Rostova',
    authorId: 'usr-1',
    authorName: 'Janaki Pawar',
    isPinned: false,
    createdAt: '2026-05-18T10:00:00Z',
    updatedAt: '2026-05-18T10:00:00Z',
  },
  {
    id: 'not-3',
    title: 'Vertex Financial - Key Security & Compliance Requirements',
    content: 'Security questionnaire cleared: SOC2 Type II, ISO 27001, end-to-end data encryption at rest, automated audit logging for role-based access.',
    tags: ['Compliance', 'Security', 'FinServ'],
    category: 'General',
    relatedToType: 'Account',
    relatedToId: 'acc-3',
    relatedToName: 'Vertex Financial Group',
    authorId: 'usr-2',
    authorName: 'Alex Chen',
    isPinned: true,
    createdAt: '2026-07-22T16:00:00Z',
    updatedAt: '2026-07-22T16:00:00Z',
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    type: 'stage_change',
    title: 'Opportunity Advanced to Negotiation',
    description: 'Janaki Pawar moved "Apex - Global Cloud Intelligence Rollout" from Proposal to Negotiation.',
    timestamp: '2026-08-19T15:00:00Z',
    userId: 'usr-1',
    userName: 'Janaki Pawar',
    relatedToType: 'Opportunity',
    relatedToId: 'opp-1',
    relatedToName: 'Apex - Global Cloud Intelligence Rollout',
  },
  {
    id: 'act-2',
    type: 'card_scanned',
    title: 'Visiting Card Scanned & Contact Created',
    description: 'Scanned visiting card for Dr. Elena Rostova (VP of Clinical Informatics) and linked to Quantum Health BioTech.',
    timestamp: '2026-08-18T11:20:00Z',
    userId: 'usr-1',
    userName: 'Janaki Pawar',
    relatedToType: 'Contact',
    relatedToId: 'cnt-2',
    relatedToName: 'Elena Rostova',
  },
  {
    id: 'act-3',
    type: 'meeting',
    title: 'Executive Contract Review with Vertex Financial',
    description: 'Met with Victoria Sterling to finalize Phase 2 onboarding rollout plan for European branches.',
    timestamp: '2026-08-16T14:00:00Z',
    userId: 'usr-1',
    userName: 'Janaki Pawar',
    relatedToType: 'Account',
    relatedToId: 'acc-3',
    relatedToName: 'Vertex Financial Group',
  },
  {
    id: 'act-4',
    type: 'stage_change',
    title: 'Deal Closed Won 🎉',
    description: 'Vertex - Phase 2 International Advisory Expansion ($450,000) marked as Closed Won.',
    timestamp: '2026-08-10T17:00:00Z',
    userId: 'usr-1',
    userName: 'Janaki Pawar',
    relatedToType: 'Opportunity',
    relatedToId: 'opp-3',
    relatedToName: 'Vertex - Phase 2 International Advisory Expansion',
  },
  {
    id: 'act-5',
    type: 'call',
    title: 'Introductory Discovery Call with Helios MFG',
    description: 'Discussed supplier management roadmap with Klaus Weber. Scheduled requirement questionnaire.',
    timestamp: '2026-08-08T09:30:00Z',
    userId: 'usr-2',
    userName: 'Alex Chen',
    relatedToType: 'Opportunity',
    relatedToId: 'opp-4',
    relatedToName: 'Helios - Smart Manufacturing Supply CRM',
  },
];

export const INITIAL_FILES: FileDocument[] = [
  {
    id: 'fil-1',
    name: 'Apex_Cloud_Master_Services_Agreement_v3.pdf',
    size: 2450000,
    type: 'application/pdf',
    category: 'Contract',
    relatedToType: 'Opportunity',
    relatedToId: 'opp-1',
    relatedToName: 'Apex - Global Cloud Intelligence Rollout',
    uploadedBy: 'Janaki Pawar',
    uploadedAt: '2026-08-19T14:15:00Z',
  },
  {
    id: 'fil-2',
    name: 'Quantum_Health_BioTech_Visiting_Card.jpg',
    size: 1120000,
    type: 'image/jpeg',
    category: 'Card Scan',
    relatedToType: 'Contact',
    relatedToId: 'cnt-2',
    relatedToName: 'Elena Rostova',
    uploadedBy: 'Janaki Pawar',
    uploadedAt: '2026-08-18T11:20:00Z',
    fileData: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'fil-3',
    name: 'Vertex_Financial_Phase2_Signed_Order_Form.pdf',
    size: 3890000,
    type: 'application/pdf',
    category: 'Contract',
    relatedToType: 'Account',
    relatedToId: 'acc-3',
    relatedToName: 'Vertex Financial Group',
    uploadedBy: 'Janaki Pawar',
    uploadedAt: '2026-08-10T17:05:00Z',
  },
  {
    id: 'fil-4',
    name: 'Helios_Manufacturing_Enterprise_Quotation_Q3.pdf',
    size: 1540000,
    type: 'application/pdf',
    category: 'Quotation',
    relatedToType: 'Opportunity',
    relatedToId: 'opp-4',
    relatedToName: 'Helios - Smart Manufacturing Supply CRM',
    uploadedBy: 'Alex Chen',
    uploadedAt: '2026-08-12T10:30:00Z',
  },
];

// Pre-packaged realistic sample visiting cards for quick 1-click OCR demonstration!
export const SAMPLE_VISITING_CARDS = [
  {
    id: 'sample-1',
    label: 'Elena Rostova (BioTech VP)',
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    parsed: {
      salutation: 'Dr.',
      firstName: 'Elena',
      lastName: 'Rostova',
      companyName: 'Quantum Health BioTech',
      jobTitle: 'VP of Clinical Informatics',
      department: 'Bioinformatics & Research',
      email: 'e.rostova@quantumhealth.bio',
      phone: '+1 (617) 555-0143',
      mobile: '+1 (617) 843-9921',
      website: 'https://quantumhealth.bio',
      address: '400 Technology Square, Cambridge, MA 02139',
      city: 'Cambridge',
      state: 'MA',
      country: 'United States',
      postalCode: '02139',
      confidence: 96,
    },
  },
  {
    id: 'sample-2',
    label: 'Devon Takahashi (AI VP of Engineering)',
    image: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=600&auto=format&fit=crop&q=80',
    parsed: {
      salutation: 'Mr.',
      firstName: 'Devon',
      lastName: 'Takahashi',
      companyName: 'Synthetix Autonomous AI',
      jobTitle: 'VP of Software Engineering',
      department: 'Machine Intelligence',
      email: 'devon.takahashi@synthetix-ai.com',
      phone: '+1 (415) 892-0044',
      mobile: '+1 (415) 302-8819',
      website: 'https://synthetix-ai.com',
      address: '750 Mission Street, San Francisco, CA 94103',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      postalCode: '94103',
      confidence: 94,
    },
  },
  {
    id: 'sample-3',
    label: 'Sophia Lindqvist (Nordic Renewable Group)',
    image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=600&auto=format&fit=crop&q=80',
    parsed: {
      salutation: 'Ms.',
      firstName: 'Sophia',
      lastName: 'Lindqvist',
      companyName: 'Nordic Clean Energy AB',
      jobTitle: 'Head of Global Partnerships',
      department: 'Commercial Strategy',
      email: 'sophia.lindqvist@nordicclean.se',
      phone: '+46 8 505 23 100',
      mobile: '+46 70 812 34 56',
      website: 'https://nordicclean.se',
      address: 'Hamngatan 15, 111 47 Stockholm, Sweden',
      city: 'Stockholm',
      state: 'Stockholm',
      country: 'Sweden',
      postalCode: '111 47',
      confidence: 98,
    },
  },
];
